### PR TITLE
Add 'x11' to display_init driver list

### PR DESCRIPTION
**Pull request by ag6ay**
Add x11 to driver list for Pi Model B HDMI output using Raspbian Stretch

### CODE REVIEW

**Comment by ag6ay** [comment]
Fixed no output on Pi Model B HDMI video output by adding 'X11' to driver list.  Environment is Raspbian Stretch.

**Comment by n1kdo** [comment]
I hand merged your changes.  I don't know why every line was marked as changed.  Line endings?

**Comment by ag6ay** [comment]
Thanks, Jeff.  I'm unsure why the whole file showed as diff.  I edited in place under Debian.  Thank you for adjusting it.  I'll look out for cause in the future.

**Comment by n1kdo** [comment]
Yeah, well there's nothing to say that the files are not CRLF already, or
something else is not right about then.

Could be my fault.

J

**Pull request closed without merging**
